# .goreleaser.yml for hvac-proxy
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: hvac-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}
    binary: hvac-proxy

dockers_v2:
  - id: hvac-proxy
    image_templates:
      - "kwv4/hvac-proxy:{{ .Version }}"
      - "kwv4/hvac-proxy:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.version={{ .Version }}"
    # Platforms to build for
    platforms:
      - linux/amd64
      - linux/arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
